### ISSUE TITLE
Gulp eslint breaks some projects on travis

### ISSUE THREAD

**Issue by pragmaticivan** [metal/gulp-metal#33]
`SyntaxError: Use of const in strict mode.`

```
/home/travis/build/liferay/senna.js/node_modules/gulp-metal/node_modules/gulp-eslint/index.js:3
const BufferStreams = require('bufferstreams');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/liferay/senna.js/node_modules/gulp-metal/lib/tasks/index.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/liferay/senna.js/node_modules/gulp-metal/index.js:3:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/liferay/senna.js/gulpfile.js:7:13)
```

https://travis-ci.org/liferay/senna.js

**Comment by pragmaticivan** [comment]
cc @bryceosterhaus

**Comment by bryceosterhaus** [comment]
@pragmaticivan  Is this fixed by https://github.com/liferay/senna.js/commit/b35ac77a23076127d92972d543398cf09e2a024e ?

**Comment by pragmaticivan** [comment]
Using const for this case may force projects to require at least node 4 I guess. May we need a description for that or just use var instead.

**Comment by bryceosterhaus** [comment]
Ah I see, yeah we should likely bump the `engines.node` version in the package.json to be `"node": ">=4"` eslint is already requiring that, see [here](https://github.com/eslint/eslint/blob/c64b0c2ec2a8a187c4ff6ed99a9ba0fb38e2eeee/package.json#L118).

Sent a pr for the change https://github.com/metal/gulp-metal/pull/38

**Comment by eduardolundgren** [comment]
Merged. Thanks.
